### ISSUE TITLE
Codificação tela - Template

### ISSUE THREAD

**Issue by christian-lelis** [Projeto-Integrador-PI/diaZen#20]
![image](https://github.com/Anotso/diaZen/assets/111591810/ace44bd0-9327-419b-8db6-500db4387bc3)

Desenvolvimento da tela de configurações.

**Comment by Anotso** [comment]
![image](https://github.com/Projeto-Integrador-PI/diaZen/assets/40184359/330ba413-c2a4-4ffc-ab9d-c47cde35d6e8)

Na presente data a finalidade da issue foi alterada de tela de configurações para a criação do template base do projeto.

**Comment by Anotso** [comment]
Encerrada a issue com a aprovação do PR.
